export const GET_ALL_COMMENT = 'GET_ALL_COMMENT'
export const GET_ALL_COMMENT_REDUCER = 'GET_ALL_COMMENT_REDUCER'

export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'