
export const OPEN_DRAWER = 'OPEN_DRAWER'
export const CLOSE_DRAWER = 'CLOSE_DRAWER'

export const OPEN_FORM_EDIT_PROJECT = 'OPEN_FORM_EDIT_RPROJECT'
export const SUBMIT_FORM_EDIT_PROJECT = 'SUBMIT_FORM_EDIT_PROJECT'

export const OPEN_FORM_CREATE_TASK = 'OPEN_FORM_CREATE_TASK'
export const SUBMIT_FORM_CREATE_TASK = 'SUBMIT_FORM_CREATE_TASK'

