

export const GET_PROJECT_CATEGORY = 'GET_PROJECT_CATEGORY'
export const GET_PROJECT_CATEGORY_REDUCER = 'GET_PROJECT_CATEGORY_REDUCER'

export const GET_ALL_PROJECT = 'GET_ALL_PROJECT'
export const GET_ALL_PROJECT_REDUCER = 'GET_ALL_PROJECT_REDUCER'
export const GET_ALL_PROJECT_DROPDOWN = 'GET_ALL_PROJECT_DROPDOWN'
export const GET_ALL_PROJECT_DROPDOWN_REDUCER = 'GET_ALL_PROJECT_DROPDOWN_REDUCER'

export const CREATE_PROJECT = 'CREATE_PROJECT'
export const CREATE_PROJECT_REDUCER = 'CREATE_PROJECT_REDUCER'


export const EDIT_PROJECT_REDUCER = 'EDIT_PROJECT_REDUCER'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'

export const DELETE_PROJECT = 'DELETE_PROJECT'

export const GET_PROJECT_DETAILS_REDUCER = 'GET_PROJECT_DETAILS_REDUCER'
export const GET_PROJECT_DETAILS = 'GET_PROJECT_DETAILS'