
export const GET_ALL_TASK_TYPE = 'GET_ALL_TASK_TYPE'
export const GET_ALL_TASK_TYPE_REDUCER = 'GET_ALL_TASK_TYPE_REDUCER'

export const CREATE_NEW_TASK = 'CREATE_NEW_TASK'

export const TASK_DETAILS_REDUCER = 'TASK_DETAILS_REDUCER'
export const TASK_DETAILS = 'TASK_DETAILS'

export const UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS'

export const CHANGE_TASK_MODAL = 'CHANGE_TASK_MODAL'
export const CHANGE_ASSIGNEE_TASK_MODAL = 'CHANGE_ASSIGNEE_TASK_MODAL'

export const HANDLE_CHANGE_TASK_MODAL = 'HANDLE_CHANGE_TASK_MODAL'
export const UPDATE_TASK_MODAL = 'UPDATE_TASK_MODAL'
export const UPDATE_TASK_MODAL_REDUCER = 'UPDATE_TASK_MODAL_REDUCER'

export const DELETE_TASK = 'DELETE_TASK'