export const USER_SIGNIN_API = 'USER_SIGNIN_API'

export const USER_LOGIN_INFO = 'USER_LOGIN_INFO'

export const USER_SEARCH_BY_KEY = 'USER_SEARCH_BY_KEY'
export const GET_USER_SEARCH_REDUCER = 'GET_USER_SEARCH_REDUCER'

export const ASSIGN_USER_PROJECT = 'ASSIGN_USER_PROJECT'
export const DELETE_USER_PROJECT = 'DELETE_USER_PROJECT'

export const GET_USER_BY_PROJECT = 'GET_USER_BY_PROJECT'
export const GET_USER_BY_PROJECT_REDUCER = 'GET_USER_BY_PROJECT_REDUCER'

export const REMOVE_USER_ASSIGN_TASK = 'REMOVE_USER_ASSIGN_TASK'

export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_ALL_USERS_REDUCER = 'GET_ALL_USERS_REDUCER'